Feature/arc 409
viaacode/hetarchief-client pull request #104
Opened 2022-02-09 14:59 UTC by ian-emsens-shd

https://meemoo.atlassian.net/browse/ARC-409

`i18n` included in #109

2022-02-11 10:08 UTC, bertyhell requested changes
one issue with the overflow horizontal: see global remark. for the rest it looks good.

2022-02-11 10:32 UTC, andrych commented on src/modules/cp/components/RequestStatusChip/RequestStatusChip.tsx
> +const RequestStatusChip: FC<RequestStatusChipProps> = ({ className, style, status }) => {
We noemen die chips in onze code `Badge` dus ik zou die naamgeving behouden

2022-02-11 10:32 UTC, andrych commented on src/pages/beheer/aanvragen/index.tsx
> +	const columns: Column<RequestTableRow>[] = [
Ik zou deze definiëren in een const file.

2022-02-11 10:32 UTC, andrych commented on src/pages/beheer/aanvragen/index.tsx
> +									...filters,
Je hoeft die filters niet altijd terug te spreaden, enkel die je wilt updaten moet je definiëren.

2022-02-14 14:03 UTC, andrych approved these changes

2022-02-14 14:28 UTC, bertyhell commented
Maybe add some bottom margin below the table so the user knows there are no more rows. Or has that happened in a later PR where the PaginationBar was added?


![image](https://user-images.githubusercontent.com/1710840/153882634-de807123-73b8-4865-8bc3-0975faa0d582.png)

2022-02-14 14:30 UTC, bertyhell approved these changes

2022-02-14 15:23 UTC, merged