Feature/arc 400
viaacode/hetarchief-client pull request #112
Opened 2022-02-10 12:47 UTC by ian-emsens-shd

https://meemoo.atlassian.net/browse/ARC-400

2022-02-10 16:06 UTC, BavoVdg approved these changes

2022-02-11 10:28 UTC, bertyhell commented
the scrollbar is always visible on windows inside the blade
use overflow-y: auto so it is only visible when it needs to be:
![image](https://user-images.githubusercontent.com/1710840/153575929-b86cb5a3-db66-4e13-9cf2-1a5df69f131c.png)
![image](https://user-images.githubusercontent.com/1710840/153575940-cb8d0606-9910-492d-84c0-7d573d4bd13c.png)

2022-02-11 10:36 UTC, bertyhell commented
not sure if it's part of this PR's scope, but the refuse button doesn't look right yet according to the design (top)
![image](https://user-images.githubusercontent.com/1710840/153577016-11162380-6317-4f58-96ce-a4a581bef93e.png)

2022-02-11 10:53 UTC, bertyhell requested changes

2022-02-11 10:53 UTC, bertyhell commented on src/pages/beheer/aanvragen/index.tsx
> +				}}
```suggestion
				onClose={() => setSelected(undefined)}
```

2022-02-14 14:28 UTC, andrych commented on src/modules/cp/components/ApproveRequestBlade/ApproveRequestBlade.const.ts
> +export const ApproveRequestAccessDateFormatter = (date?: Date): string => {
const gaan we meestal in upper snake case definiëren APPROVE_REQUEST_ACCESS_DATE_FORMATTER maar dit lijkt me eerder een helper func, dat mag dan in `ApproveRequestBlade.utils.ts` als `formatApproveRequestAccessDate`. Als deze op meerdere plaatsen nodig zijn mag dat in de `shared/utils`

2022-02-14 14:28 UTC, andrych commented on src/modules/cp/components/ApproveRequestBlade/ApproveRequestBlade.const.ts
> +export const ApproveRequestAccessTimeFormatter = (date?: Date): string => {
Idem, je kan dit zelfs in een generieke functie gieten waarbij je uw format als parameter meegeeft in `shared/utils/date.ts`:
```typescript
export const formatWithLocale = (format: string, date?: Date): string => {
    const locale = getLocaleFromi18nLanguage(i18n?.language || '');
    return date ? format(date, format, { locale }) : '';
}
```

2022-02-14 14:28 UTC, andrych commented on src/modules/cp/components/DeclineRequestBlade/DeclineRequestBlade.tsx
> +	return <Blade {...props} title={t('Aanvraag afkeuren')} />;
Deze nog extracten.

2022-02-14 14:54 UTC, ian-emsens-shd commented on src/modules/cp/components/DeclineRequestBlade/DeclineRequestBlade.tsx
> +	return <Blade {...props} title={t('Aanvraag afkeuren')} />;
Fixed in #119

2022-02-14 15:23 UTC, merged