Bugfix/feedback part 4
viaacode/hetarchief-client pull request #153
Opened 2022-02-25 15:29 UTC by BavoVdg

[ARC-372](https://meemoo.atlassian.net/jira/software/c/projects/ARC/boards/36?modal=detail&selectedIssue=ARC-372)
[ARC-195](https://meemoo.atlassian.net/jira/software/c/projects/ARC/boards/36?modal=detail&selectedIssue=ARC-195)
[ARC-245](https://meemoo.atlassian.net/jira/software/c/projects/ARC/boards/36?modal=detail&selectedIssue=ARC-245)
[ARC-256](https://meemoo.atlassian.net/jira/software/c/projects/ARC/boards/36?modal=detail&selectedIssue=ARC-256)
[ARC-399](https://meemoo.atlassian.net/jira/software/c/projects/ARC/boards/36?modal=detail&selectedIssue=ARC-399)
[ARC-188](https://meemoo.atlassian.net/jira/software/c/projects/ARC/boards/36?modal=detail&selectedIssue=ARC-188)

2022-02-28 09:49 UTC, bertyhell commented
https://meemoo.atlassian.net/browse/ARC-372
this still doesn't seem to fill in the advanced form:
![image](https://user-images.githubusercontent.com/1710840/155961729-269773d5-f355-46c0-9dfe-dfa369322796.png)

2022-02-28 09:59 UTC, bertyhell commented
https://meemoo.atlassian.net/browse/ARC-399

Het verwijderen werkt nog niet correct, en klikken op het vergrootglas heeft nog steeds issues:

https://user-images.githubusercontent.com/1710840/155963282-51ca2905-e1e6-4adf-9c37-f9a57b5be1b8.mp4

2022-02-28 10:17 UTC, bertyhell commented
https://meemoo.atlassian.net/browse/ARC-188
Door die outline te verbergen, is dat notifications menu niet meer makkelijk accessible via het toetsenbord.
Als ik overal de outline: none en outline: transparent css weg haal lijkt dit wil correct te werken:
outline is enkel zichtbaar als je er met het keyboard naar toe gaat en niet als je erop klikt.

2022-02-28 10:18 UTC, bertyhell requested changes
see global remarks on the PR

2022-02-28 11:22 UTC, BavoVdg commented
> https://meemoo.atlassian.net/browse/ARC-372 this still doesn't seem to fill in the advanced form: ![image](https://user-images.githubusercontent.com/1710840/155961729-269773d5-f355-46c0-9dfe-dfa369322796.png)

@bertyhell ik heb dat precies niet voor 🤔 

https://user-images.githubusercontent.com/85545258/155975025-4b8dd5be-3c78-42c3-b71b-a328c218853e.mp4

2022-02-28 15:02 UTC, BavoVdg commented
> https://meemoo.atlassian.net/browse/ARC-399
> 
> Het verwijderen werkt nog niet correct, en klikken op het vergrootglas heeft nog steeds issues:
> 
>  search-visit-requests.mp4 
> eens gefixt zal deze ook gesloten morgen worden: https://meemoo.atlassian.net/browse/ARC-530

@bertyhell zou opgelost moeten zijn.

2022-03-01 13:23 UTC, bertyhell commented
stappen:
- ga naar de homepage
- zoek reading room op 'vlaams'
- druk op enter
- klik opnieuw in het zoek veld en druk opnieuw op enter

verwacht resultaat: de zoekterm blijft staan en de resultaten veranderen niet

huidig resultaat: de zoekterm verdwijnt en de resultaten blijven staan


meestal krijg je zo'n vreemd behavior doordat er in de SearchBar component de input als state wordt opgeslagen. Maar dit word wss beter enkel opgeslagen in de aanvragen/index component. Anders werken die 2 useState's elkaar tegen.

2022-03-01 13:24 UTC, bertyhell requested changes
strange behavior in reading room searchbar, see remark above

2022-03-02 11:39 UTC, BavoVdg commented
> strange behavior in reading room searchbar, see remark above

@bertyhell should be fixed.

2022-03-04 08:43 UTC, bertyhell approved these changes

2022-03-04 13:54 UTC, merged