feat(arc-522): playwright setup + initial test T004
viaacode/hetarchief-client pull request #154
Opened 2022-02-25 16:23 UTC by bertyhell

https://docs.google.com/spreadsheets/d/1yGNKFkeE-2Kv2mADOvKzDK3BYTvoiSbVO6pAsuoG5P8/edit#gid=473791225

Stap # | Stap detail | Verwacht resultaat
-- | -- | --
1 | Navigeer naar homepagina van BZT | Homepagina opent
2 | Klik op 'Inloggen of registreren' | Modal 'Inloggen of registreren' opent
3 | Klik op 'Inloggen met Het Archief-account' | Loginformulier opent (idp.hetarchief)
4 | Vul e-mailadres en wachtwoord in en klik op 'Inloggen' | User is ingelogd en landt op homepagina. User krijgt geen gebruiksvoorwaarden te zien

![automated-test](https://user-images.githubusercontent.com/1710840/155750363-84da37f7-2ab4-4d93-a455-cc6c1ab92535.gif)

```
> hetarchief-client@0.3.0 test:e2e:debug
> cross-env PWDEBUG=console dotenv -e .env.local npx playwright test --browser=firefox --headed --workers=1 --retries=0 --maxFailures=1 tests/auth/login-with-redirect.spec.ts

Running 1 test using 1 worker
·

  1 passed (6s)

Process finished with exit code 0
```

2022-03-02 13:15 UTC, BavoVdg commented
Klopt het dat de ENV vars nog niet geüpdated zijn in OnePassword? Ik vind nergens een value voor `TEST_ENDPOINT`

2022-03-02 13:55 UTC, BavoVdg requested changes
Zie comment

2022-03-07 14:52 UTC, bertyhell commented
> Klopt het dat de ENV vars nog niet geüpdated zijn in OnePassword? Ik vind nergens een value voor `TEST_ENDPOINT`

@BavoVdg fixed

2022-03-08 10:49 UTC, BavoVdg approved these changes

2022-03-08 13:13 UTC, merged