fix(auth): hide tos on logged in home
viaacode/hetarchief-client pull request #155
Opened 2022-02-28 09:44 UTC by bertyhell

2022-03-02 12:40 UTC, BavoVdg commented
Als ik van de homepage naar een pagina navigeer waar je de TOS voor moet accepteren, dan kom ik op de TOS pagina, maar:
- Als ik dan op annuleer klik, ga ik niet terug naar de homepagina
- Als ik via de browser terug wil gaan (back button) ga ik niet terug naar de homepagina

2022-03-02 13:55 UTC, BavoVdg requested changes
Zie comment

2022-03-07 14:50 UTC, bertyhell commented
> Als ik van de homepage naar een pagina navigeer waar je de TOS voor moet accepteren, dan kom ik op de TOS pagina, maar:
> 
> * Als ik dan op annuleer klik, ga ik niet terug naar de homepagina
> * Als ik via de browser terug wil gaan (back button) ga ik niet terug naar de homepagina

@BavoVdg should be fixed. Should now be able to return using the back button, or when you click cancel, you'll be redirected to the home page

2022-03-08 10:26 UTC, BavoVdg approved these changes

2022-03-08 12:43 UTC, ian-emsens-shd commented on src/modules/shared/utils/tos.ts
> +	}
Note: legal pitfall, liever luid crashen dan stillekes skippen

2022-03-08 12:46 UTC, ian-emsens-shd commented on src/pages/gebruiksvoorwaarden/index.tsx
> +		await router.push(ROUTES.home);
Mag verder verwijderd worden
https://meemoo.atlassian.net/browse/ARC-175?focusedCommentId=29584

2022-03-08 12:46 UTC, ian-emsens-shd approved these changes

2022-03-08 13:12 UTC, merged