Feature/arc 253 ook interessant
viaacode/hetarchief-client pull request #218
Opened 2022-04-04 08:50 UTC by BavoVdg

- db integratie ook interessant

2022-04-05 07:45 UTC, ian-emsens-shd requested changes

2022-04-05 07:45 UTC, ian-emsens-shd commented on src/modules/media/hooks/get-media-similar.ts
> +			keepPreviousData: true,
Is dit geen default config?

2022-04-05 07:45 UTC, ian-emsens-shd commented on src/pages/leeszaal/[readingRoomSlug]/[objectId]/index.tsx
> +import { toLower } from 'lodash';
Vermijd `lodash`, gebruik `lodash-es` of `toLowerCase`

2022-04-05 07:45 UTC, ian-emsens-shd commented on src/pages/leeszaal/[readingRoomSlug]/[objectId]/index.tsx
> +				})
separate map function for legibility; `const mapSimilarData = () ...`

2022-04-05 07:45 UTC, ian-emsens-shd commented on src/pages/leeszaal/[readingRoomSlug]/[objectId]/index.tsx
> +													title: 'Ook interessant',
i18n

2022-04-05 07:45 UTC, ian-emsens-shd commented on src/styles/pages/_object-detail.scss
> +	}
Replace with https://github.com/viaacode/hetarchief-client/blob/release/v0.7.0/src/styles/utilities/_text.scss#L11-L13

2022-04-08 06:41 UTC, ian-emsens-shd approved these changes

2022-04-08 07:31 UTC, bertyhell approved these changes

2022-04-08 07:40 UTC, merged