Feature/arc 584 gerelateerde objecten
viaacode/hetarchief-client pull request #219
Opened 2022-04-04 08:57 UTC by BavoVdg

- related objects component
- DB integratie

⚠️ Hoe testen?
1. Update een `object_ie` zodat er twee zijn met dezelfde `meemooIdentifier`. Dit kan met volgende query:
```
mutation MyQuery {
  update_object_ie_by_pk(pk_columns: {schema_identifier: "09f17b37445c4ce59f645c2d5db9dbf8dbee79eba623459caa8c6496108641a0900618cb6ceb4e9b8ad907e47b980ee3"} _set: {meemoo_identifier: "8911p09j1g"}) {
    meemoo_identifier
    maintainer {
      schema_identifier
    }
    schema_identifier
  }
}
```
2. Surf naar volgende url: http://localhost:3200/leeszaal/OR-rf5kf25/49b1bf8894004fd49aeaba36cfc5a958d5c32a4566244999a862e80b498a2c7c7bee152896204294938534fc7f3c6793

2022-04-05 08:04 UTC, ian-emsens-shd requested changes

2022-04-05 08:04 UTC, ian-emsens-shd commented on src/styles/pages/_object-detail.scss
> +		// TODO: if related objects
Niet duidelijk wat hier nog moet gebeuren

2022-04-05 08:04 UTC, ian-emsens-shd commented on src/styles/pages/_object-detail.scss
> +		background-color: $platinum;
Vervang met https://github.com/viaacode/hetarchief-client/blob/release/v0.7.0/src/styles/utilities/_background.scss#L9

2022-04-05 08:04 UTC, ian-emsens-shd commented on src/styles/pages/_object-detail.scss
> +			background-color: red;
`red`

2022-04-05 08:04 UTC, ian-emsens-shd commented on src/styles/utilities/_spacers.scss
> +	"10": 1rem,
Liever afronden naar een meervoud van `8` dan echt 1:1 design volgen.

2022-04-08 07:49 UTC, bertyhell approved these changes
bonus points voor de test query :D

2022-04-08 08:10 UTC, merged