feat(textarea): add styling and stories
viaacode/hetarchief-client pull request #22
Opened 2021-12-16 08:20 UTC by andrych

* Added Textarea component styling and stories

2021-12-20 10:45 UTC, ian-emsens-shd approved these changes

2021-12-20 10:48 UTC, BavoVdg approved these changes

2021-12-20 10:49 UTC, ian-emsens-shd requested changes
`height` and `width` props appear to be missing their scss implementation

2021-12-23 09:40 UTC, andrych commented
> `height` and `width` props appear to be missing their scss implementation

@ian-emsens-shd wordt opgevangen via variants prop in https://github.com/viaacode/react-components/pull/1

2021-12-23 09:40 UTC, merged