Feature/arc 391
viaacode/hetarchief-client pull request #226
Opened 2022-04-06 12:48 UTC by ian-emsens-shd

https://meemoo.atlassian.net/browse/ARC-391

Requires https://github.com/viaacode/hetarchief-proxy/pull/130

2022-04-07 09:36 UTC, BavoVdg commented on src/styles/pages/_visit-requested.scss
> +			bottom: -56px;
`px` -> `rem`. Ik dacht dat we overal `rem` gingen gebruiken voor consistentie. Correct me if I'm wrong :)

2022-04-07 09:42 UTC, BavoVdg requested changes
- Ik krijg een grote witte balk boven de afbeelding en tekst. Deze is een pak kleiner is het [design](https://xd.adobe.com/view/86b0be3f-d968-4a98-7784-d5d00cd42f98-f081/screen/a70cca6c-1a19-45fa-beff-a9137f259af6/specs/). 
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/85545258/162169944-7b5db27f-9fb7-4e92-988a-688c12710b51.png">

- Ik word niet naar de leeszaal/... geredirect nadat ik een notificatie krijg dat mijn toegang goedgekeurd/afgekeurd is.

- Ik krijg altijd de `404 - geen toegang` als ik een leeszaal probeer te bezoeken.

2022-04-08 08:54 UTC, bertyhell commented
Ik zie dit, nadat ik een aanvraag doe op het homescreen:
![image](https://user-images.githubusercontent.com/1710840/162401693-5b33912a-6cda-4821-9526-5b3fae845f6b.png)


De titel "We hebben je aanvraag ontvangen" zie ik niet staan.

Als ik naar de url zelf surf:
http://localhost:3200/OR-154dn75

Dan word ik geredirect naar de homepage met een lege notificatie 🤯 
![image](https://user-images.githubusercontent.com/1710840/162401705-97a9fe7d-e049-4bf5-89d5-68f89606f440.png)

2022-04-08 08:55 UTC, bertyhell requested changes
see global remark

2022-04-08 09:04 UTC, merged