Feature/arc 164 hero niet ingelogd
viaacode/hetarchief-client pull request #26
Opened 2021-12-23 09:22 UTC by BavoVdg

Hero component voor niet ingelogde gebruikers.

![image](https://user-images.githubusercontent.com/85545258/147218511-4cdbb974-f926-4844-984f-2b178b19a880.png)
![image](https://user-images.githubusercontent.com/85545258/147218557-a72e366f-ef96-4542-8331-a389848cd22d.png)

2021-12-23 10:10 UTC, andrych reviewed
Je mag deze ook ineens al op de juiste pagina zetten in `/pages`

2021-12-23 10:10 UTC, andrych commented on src/modules/shared/components/Hero/Hero.module.scss
> +// Vaste hoogte?
Yes, hero mag een fixed height hebben

2021-12-23 10:10 UTC, andrych commented on src/modules/shared/components/Hero/Hero.types.ts
> +export interface HeroLink {
Als je dit vaak ziet terugkomen mag je dat gerust in de shared types zetten als `ComponentLink` of iets dergelijk

2021-12-23 12:52 UTC, BavoVdg commented on src/modules/shared/components/Hero/Hero.module.scss
> +// Vaste hoogte?
De hero reflow ziet er nu zo uit. Dan blijven de verhoudingen proper

https://user-images.githubusercontent.com/85545258/147243098-59796204-beec-468d-a9a8-26f11b6fba25.mp4

.

2021-12-23 14:06 UTC, ian-emsens-shd requested changes
Ik had zin in een in-depth review 😬 dus bij deze...

2021-12-23 14:06 UTC, ian-emsens-shd commented on src/modules/shared/components/Hero/__mocks__/hero.tsx
> +export const heroImage = { name: 'hero.png', alt: 'hero image' };
En ook; Is het nodig om hier een `__mocks__` folder voor bij te maken? Ik ben persoonlijk fan van een zo plat mogelijke structuur maar ik weet niet wat hier best practice is op vlak van testing.

2021-12-23 14:06 UTC, ian-emsens-shd commented on src/pages/index.tsx
> +			/>
```suggestion
			<Hero {...heroMock} />
```

2021-12-23 14:06 UTC, ian-emsens-shd commented on src/pages/index.tsx
> +} from '@shared/components/Hero/__mocks__/hero';
```suggestion
import { heroMock } from '@shared/components/Hero/__mocks__/hero';
```

2021-12-23 14:06 UTC, ian-emsens-shd commented on src/modules/shared/components/Hero/Hero.stories.tsx
> +};
```suggestion
Default.args = {
	...mockHero,
	title: 'Welkom in de digitale zaal/bezoekerszaal/space/ruimte/locatie'
};
```

2021-12-24 07:42 UTC, BavoVdg commented on src/modules/shared/components/Hero/Hero.module.scss
> +		max-width: 35rem;
`320px` is het kleinste dat lukt zonder dat de tekst layout verandert tov het design.

2021-12-24 07:46 UTC, BavoVdg commented on src/modules/shared/components/Hero/__mocks__/hero.tsx
> +export const heroImage = { name: 'hero.png', alt: 'hero image' };
De `__mocks__` folder wordt ook gebruikt om manual mocks te maken van de module ([jest docs](https://jestjs.io/docs/manual-mocks)). Aangezien de meest voorname use case voor deze data voor testing is, lijkt het me logisch dat die onder `__mocks__` terecht komt.

2021-12-24 13:56 UTC, ian-emsens-shd approved these changes

2021-12-24 14:10 UTC, merged