Feature/arc 529 cp info aanvragen blade
viaacode/hetarchief-client pull request #321
Opened 2022-05-02 10:08 UTC by BavoVdg

[ARC-529](https://meemoo.atlassian.net/browse/ARC-529)

2022-05-03 14:11 UTC, bertyhell approved these changes

2022-05-03 14:37 UTC, BavoVdg commented on src/modules/home/components/RequestAccessBlade/RequestAccessBlade.tsx
> +	});
Fixed!

2022-05-04 07:36 UTC, ian-emsens-shd requested changes

2022-05-04 07:36 UTC, ian-emsens-shd commented on src/modules/home/components/RequestAccessBlade/RequestAccessBlade.tsx
> +						spaceServiceDescription={space.serviceDescription || undefined}
`space`-prefix voor deze attributen is overbodig, ofwel 1 `space` input of de typing overerven van het `space`-type in deze blade

2022-05-04 07:36 UTC, ian-emsens-shd commented on src/modules/shared/components/VisitSummary/VisitSummary.tsx
> -	spaceServiceDescription = '<b>banaan</b>',
😅

2022-05-05 11:55 UTC, bertyhell approved these changes

2022-05-05 12:51 UTC, ian-emsens-shd approved these changes

2022-05-05 12:51 UTC, merged