Bugfix/arc 256 mobile navigation
viaacode/hetarchief-client pull request #324
Opened 2022-05-02 13:12 UTC by BavoVdg

- 'Bezoekersruimte' in hamburgermenu navigeert naar homepagina
- Sluit hamburger na navigatie
- Fix hover states in hamburgermenu

2022-05-03 14:14 UTC, bertyhell commented
clicking on the "bezoekersruimtes" link in the hamburger when already on the homepage does not close the hamburger:
![image](https://user-images.githubusercontent.com/1710840/166470210-1a641225-9653-4683-abfb-3cb1beec546a.png)

2022-05-03 14:19 UTC, bertyhell commented
only the first case has a hover state, the others don't:
![image](https://user-images.githubusercontent.com/1710840/166471167-e1ae29f7-f130-4db0-85ef-356c548bba74.png)

2022-05-03 14:26 UTC, bertyhell requested changes

2022-05-03 14:26 UTC, bertyhell commented on src/modules/navigation/components/Navigation/NavigationSection/NavigationSection.tsx
> +	}, [history, currentPath, isHamburgerMenuOpen]);
Can't you handle this closing in the onClick handler of a navigation item or maybe in the onClick handler of the wrapper around the navigation items.
Or doesn't the event bubble to the top anymore?

2022-05-03 14:54 UTC, BavoVdg commented
@bertyhell 
- Added hover states
- Dropdown closes on click (handled by dropdown wrapper)

2022-05-03 15:36 UTC, bertyhell approved these changes

2022-05-04 08:08 UTC, ian-emsens-shd approved these changes

2022-05-04 08:09 UTC, merged