fix(arc-784): active state in hamburger menu
viaacode/hetarchief-client pull request #331
Opened 2022-05-03 11:26 UTC by BavoVdg

- Active state in hamburger menu (bold)
- Fiks 'Bezoekersruimtes) active state in leeszalen en detailpagina's

2022-05-03 15:26 UTC, bertyhell approved these changes

2022-05-04 08:17 UTC, ian-emsens-shd requested changes

2022-05-04 08:17 UTC, ian-emsens-shd commented on src/modules/navigation/components/Navigation/NavigationList/NavigationList.tsx
> +							[styles['c-navigation__item--active-mobile']]: item.activeMobile,
Waarom hier een onderscheid in twee klasses ipv. een media-query?

2022-05-05 11:57 UTC, bertyhell approved these changes

2022-05-05 13:00 UTC, ian-emsens-shd requested changes
Waarom `c-navigation__dropdown-item--active-mobile` & `c-navigation__dropdown-item--active-desktop` apart en niet gewoon `c-navigation__dropdown-item--active`?

Een `dropdown-item` op "desktop"-resolutie gaat nog steeds `c-navigation__dropdown-item--active-mobile` hebben

2022-05-06 07:50 UTC, BavoVdg commented
> Waarom `c-navigation__dropdown-item--active-mobile` & `c-navigation__dropdown-item--active-desktop` apart en niet gewoon `c-navigation__dropdown-item--active`?
> 
> Een `dropdown-item` op "desktop"-resolutie gaat nog steeds `c-navigation__dropdown-item--active-mobile` hebben

Fixed

2022-05-06 08:43 UTC, merged