fix(masonary): add fix for masonary sidebar height issue
viaacode/hetarchief-client pull request #341
Opened 2022-05-03 18:27 UTC by bertyhell

2022-05-04 08:59 UTC, ian-emsens-shd requested changes
Voor mij geen oplossing, aangezien de filter in volgende phases niet meer 2x card-height gaat zijn.

![image](https://user-images.githubusercontent.com/90180417/166651438-f81835e0-5954-4ed9-b9a7-73eb92e427dc.png)

2022-05-05 14:28 UTC, bertyhell commented
Ineke bekijkt deze nog met het team

2022-05-05 15:04 UTC, bertyhell commented
beslissingen van ineke toegevoegd in: https://meemoo.atlassian.net/browse/ARC-261?focusedCommentId=31334

2022-05-05 15:12 UTC, BavoVdg approved these changes

2022-05-06 07:51 UTC, ian-emsens-shd approved these changes

2022-05-06 08:17 UTC, merged