Feature/arc 204 list navigation component
viaacode/hetarchief-client pull request #35
Opened 2022-01-05 11:57 UTC by BavoVdg

[ARC-204](https://meemoo.atlassian.net/jira/software/c/projects/ARC/boards/36?modal=detail&selectedIssue=ARC-204)

# List navigation component
![image](https://user-images.githubusercontent.com/85545258/148213571-08f86384-1101-4754-aed6-14edccba1ba9.png)

🧪  getest in Chrome, Firefox, Safari

2022-01-06 08:35 UTC, andrych approved these changes

2022-01-06 08:35 UTC, andrych commented on src/modules/shared/components/ListNavigation/ListNavigation.module.scss
> +		padding: 0;
Ik heb een `%reset-list` placeholder toegevoegd in de styles onder `abstracts/`
Je kan die hiervoor gebruiken.

2022-01-07 09:43 UTC, ian-emsens-shd requested changes

2022-01-07 09:43 UTC, ian-emsens-shd commented on src/modules/shared/components/ListNavigation/ListNavigation.tsx
> +	const renderdivider = () => {
`camelCase`

2022-01-07 09:43 UTC, ian-emsens-shd commented on src/modules/shared/components/ListNavigation/ListNavigation.tsx
> +					}
```suggestion
				return (
					<li
						className={styles['c-list-navigation__list-item']}
						key={`list-item-${index}`}
						role="listitem"
					>
						{isLink(item) ? renderLink(item) : renderButton(item as ListNavigationButton)}
					</li>
				);
```

2022-01-07 11:34 UTC, BavoVdg commented on src/modules/shared/components/ListNavigation/ListNavigation.tsx
> +					}
fixed!

2022-01-07 11:35 UTC, ian-emsens-shd approved these changes

2022-01-07 15:49 UTC, merged