fix(arc-823): Show the no-access page for pages without permissions
viaacode/hetarchief-client pull request #362
Opened 2022-05-06 12:20 UTC by bertyhell

2022-05-11 12:42 UTC, BavoVdg commented
Dit werkt nog niet voor `http://localhost:3200/admin/leeszalenbeheer/leeszalen`

2022-05-11 12:42 UTC, BavoVdg requested changes
Zie comment

2022-05-12 07:36 UTC, bertyhell commented
> Dit werkt nog niet voor `http://localhost:3200/admin/leeszalenbeheer/leeszalen`

Fixed for all pages:
![image](https://user-images.githubusercontent.com/1710840/168017232-1d28caf8-9d12-41f9-aba8-49dda2e8e416.png)

2022-05-12 11:10 UTC, ian-emsens-shd requested changes

2022-05-12 11:10 UTC, ian-emsens-shd commented on src/modules/shared/hoc/withAllRequeredPermissions.tsx
>  export const withAllRequiredPermissions = (
Typo in filename (`Requered`), matcht niet meer met naam van `const`

2022-05-12 11:10 UTC, ian-emsens-shd commented on src/modules/shared/hoc/withAnyRequeredPermissions.tsx
>  export const withAnyRequiredPermissions = (
Typo in filename (`Requered`), matcht niet meer met naam van `const`

2022-05-13 07:49 UTC, ian-emsens-shd approved these changes

2022-05-13 07:49 UTC, merged