feat(arc-440): implement placeholder for insufficient licenses
viaacode/hetarchief-client pull request #365
Opened 2022-05-06 15:15 UTC by BavoVdg

[ARC-440](https://meemoo.atlassian.net/browse/ARC-440)
- Implement placeholder wanneer de essence niet getoond mag worden (als `BEZOEKERTOOL-CONTENT` licentie ontbreekt)

2022-05-11 09:46 UTC, bertyhell requested changes

2022-05-11 09:46 UTC, bertyhell commented on public/locales/nl/common.json
> +  "modules/media/const/index___dit-object-bevat-geen-licentie-voor-online-raadpleging-breng-een-bezoek-aan-de-leeszaal": "Dit object bevat geen licentie voor online raadpleging. Breng een bezoek aan
```suggestion
  "modules/media/const/index___dit-object-bevat-geen-licentie-voor-online-raadpleging-breng-een-bezoek-aan-de-leeszaal": "Dit object bevat geen licentie voor online raadpleging. Breng een bezoek aan de bezoekersruimte.",
```

2022-05-11 09:46 UTC, bertyhell commented on public/locales/nl/common.json
> +  "modules/media/const/index___je-kan-het-object-enkel-bekijken-tijdens-een-fysiek-bezoek-aan-de-leeszaal": "Je kan het object enkel bekijken tijdens een fysiek bezoek aan de leeszaal.",
```suggestion
  "modules/media/const/index___je-kan-het-object-enkel-bekijken-tijdens-een-fysiek-bezoek-aan-de-leeszaal": "Je kan dit object enkel bekijken tijdens een fysiek bezoek aan de bezoekersruimte.",
```

2022-05-11 09:46 UTC, bertyhell commented on public/locales/nl/common.json
> +  "modules/media/const/index___je-kan-het-object-enkel-bekijken-tijdens-een-fysiek-bezoek-aan-de-leeszaal": "Je kan het object enkel bekijken tijdens een fysiek bezoek aan de leeszaal.",
bij voorkeur ook de translation key fixen in zowel de common.js file als in de .ts file

2022-05-11 09:47 UTC, bertyhell commented
I changed an item in the database, but the video is still there:
![image](https://user-images.githubusercontent.com/1710840/167821491-5c1f0f46-525e-43f7-ad07-c04f6b33d009.png)

2022-05-12 11:17 UTC, ian-emsens-shd approved these changes

2022-05-13 10:45 UTC, ian-emsens-shd commented
Video wordt niet getoond
![image](https://user-images.githubusercontent.com/90180417/168267872-6fe816f0-9296-4570-9d34-75b38275ea45.png)

2022-05-13 10:45 UTC, merged