fix(arc-162): add resize listener on body to update zendesk positioning
viaacode/hetarchief-client pull request #404
Opened 2022-05-27 12:51 UTC by bertyhell

2022-05-31 14:55 UTC, BavoVdg commented on src/modules/shared/components/ZendeskWrapper/ZendeskWrapper.tsx
> +			console.log({
👀

2022-05-31 15:07 UTC, BavoVdg requested changes
De knop verspringt wanneer de trigger om de knop sticky te positioneren lijkt te laat te zijn.
Zie video

2022-06-01 10:51 UTC, bertyhell commented
> De knop verspringt wanneer de trigger om de knop sticky te positioneren lijkt te laat te zijn.
> Zie video

klopt, maar dat is een minor issue. Voorlopig zou ik dat gerust laten. Voor meemoo is het vooral van belang dat die knop niet over het logo van de vlaamse overheid komt.

2022-06-02 13:45 UTC, BavoVdg approved these changes

2022-06-02 13:58 UTC, merged