fix(arc-861): set filter with when masonry isn't initialized
viaacode/hetarchief-client pull request #417
Opened 2022-05-31 15:34 UTC by bertyhell

![image](https://user-images.githubusercontent.com/1710840/171212813-c3a8d556-355a-4459-a50d-913278ee5430.png)
![image](https://user-images.githubusercontent.com/1710840/171212822-87b32970-c458-480b-9445-87688d6f16fe.png)

2022-06-01 09:21 UTC, BavoVdg commented on src/modules/shared/components/MediaCardList/MediaCardList.tsx
> +				'c-media-card-list',
Het lijkt me niet de bedoeling om global styles te gebruiken in een component. Ik zou hier css modules gebruiken of de type extenden met `DefaultComponentProps` en dan zo de globale class meegeven.

2022-06-01 09:23 UTC, BavoVdg commented on src/styles/pages/_visitor-space.scss
> +.c-media-card-list {
Zou idealiter een `p-` class zijn die meegegeven wordt aan het component.

2022-06-01 09:23 UTC, BavoVdg requested changes
Breedtes kloppen niet over verschillende tabs
https://user-images.githubusercontent.com/85545258/171372119-6387ee69-1c0a-4f6d-a9b9-35ff60cbdf34.mov

2022-06-01 09:53 UTC, bertyhell commented
> Breedtes kloppen niet over verschillende tabs

Fixed:

https://user-images.githubusercontent.com/1710840/171377972-ad27a230-c927-4515-846c-7ca8fa7bc7b9.mp4

2022-06-02 13:56 UTC, BavoVdg commented on src/modules/shared/components/MediaCardList/MediaCardList.tsx
> +const MediaCardList: FC<MediaCardListProps & DefaultComponentProps> = ({
In de rest van de client wordt de uitbreiding met `DefaultComponenProps` in de `.types` files gedaan. Ik zou dat voor consistentie hier ook zo doen. Wel approved

2022-06-02 16:41 UTC, merged