fix(arc-256): Add link for "beheer" to cp visitor requests page
viaacode/hetarchief-client pull request #451
Opened 2022-06-08 11:05 UTC by bertyhell

https://meemoo.atlassian.net/browse/ARC-256

2022-06-08 12:52 UTC, BavoVdg commented on src/modules/navigation/components/Navigation/Navigation.consts.tsx
>  					className: linkCls(['u-color-black', 'u-color-white:md']),
```suggestion
					className: linkCls(['u-color-black', 'u-color-white:md', styles['c-navigation__link--dropdown']]),
```

Hover effect in de mobile dropdown

2022-06-08 12:55 UTC, BavoVdg requested changes
Als je op desktop op beheer klikt gaat de dropdown open tot de navigatie afgerond is en dat sluit deze weer.

2022-06-09 14:58 UTC, BavoVdg approved these changes
Zie comment classes

2022-06-09 16:38 UTC, bertyhell commented on src/modules/navigation/components/Navigation/Navigation.consts.tsx
> +					className: linkCls(
voor deze stond de class: 'u-whitespace-nowrap', er niet bij. Of moet die er eigenlijk ook bij?

2022-06-10 07:28 UTC, bertyhell commented on src/modules/navigation/components/Navigation/Navigation.consts.tsx
> +					className: linkCls(
ziet ernaar uit van wel

2022-06-10 07:28 UTC, merged