fix(arc-251): update zoekresultaten scherm
viaacode/hetarchief-client pull request #510
Opened 2022-08-08 13:34 UTC by bartnaessens

enkel start je zoektocht voor eerste search; daarna alle resultaten

<img width="1179" alt="Schermafbeelding 2022-08-08 om 15 34 09" src="https://user-images.githubusercontent.com/8707395/183430408-bda1225d-9495-4c0d-b865-e4de00ae3b5f.png">
<img width="1181" alt="Schermafbeelding 2022-08-08 om 15 33 45" src="https://user-images.githubusercontent.com/8707395/183430462-d25db036-c902-47be-ac41-1413323b7eb0.png">

2022-08-09 06:56 UTC, ian-emsens-shd requested changes

2022-08-09 06:56 UTC, ian-emsens-shd commented on src/modules/visitor-space/const/index.tsx
> +	focus: undefined,
Ongebruikte query param?

2022-08-09 06:56 UTC, ian-emsens-shd commented on src/modules/visitor-space/const/index.tsx
> +	hasSearched: undefined,
Verplaatsen naar shared const

2022-08-09 09:53 UTC, bartnaessens commented on src/modules/visitor-space/const/index.tsx
> +	focus: undefined,
idd, leftover van tussenoplossing. deleted

2022-08-09 09:53 UTC, bartnaessens commented on src/modules/visitor-space/const/index.tsx
> +	hasSearched: undefined,
done

2022-08-11 12:07 UTC, bertyhell approved these changes

2022-08-11 12:33 UTC, merged