Feature/arc 1110
viaacode/hetarchief-client pull request #582
Opened 2022-09-30 08:49 UTC by ian-emsens-shd

https://meemoo.atlassian.net/browse/ARC-1110

Requires https://github.com/viaacode/hetarchief-proxy/pull/254

2022-09-30 12:58 UTC, bertyhell commented on src/modules/media/types/index.ts
>  	premisIsPartOf?: string;
moeten we niet het veld premisIsPartOf wegnemen ipv premisRelationship?

Volgens de metadata set op confluence:
In de taak zeggen ze: alles onder relations wegnemen:
![image](https://user-images.githubusercontent.com/1710840/193274729-233e976a-95de-49fb-bf99-dee1a27c1943.png)

2022-09-30 12:58 UTC, bertyhell requested changes
see code remark

2022-10-03 07:41 UTC, bertyhell approved these changes
If charlotte signs off on this, it is good for me

2022-10-03 09:25 UTC, ian-emsens-shd commented
> If charlotte signs off on this, it is good for me

https://meemoo.atlassian.net/browse/ARC-1109?focusedCommentId=34838
https://github.com/viaacode/hetarchief-proxy/pull/255

2022-10-03 09:30 UTC, merged