Feature/arc 1246
viaacode/hetarchief-client pull request #604
Opened 2023-01-11 08:29 UTC by silkederudder-shd

<img width="2103" alt="image" src="https://user-images.githubusercontent.com/77958553/211755964-7f7544d3-4c0b-4585-b56a-08a49d8b91b6.png">

2023-01-11 11:58 UTC, WardVerc1 approved these changes

2023-01-23 09:05 UTC, bertyhell requested changes

2023-01-23 09:05 UTC, bertyhell commented on public/locales/nl/common.json
> +  "modules/media/const/index___er-ging-iets-mis-bij-het-ophalen-van-het-afspeel-token": "Er ging iets mis bij het afspelen. Probeer het opnieuw. ",
remove trailing space

2023-01-23 09:05 UTC, bertyhell commented on public/locales/nl/common.json
> +  "pages/admin/mijn-materiaalaanvragen/index___mijn-materiaalaanvragen-meta-omschrijving": "",
Add a default translation in the common.json file for these 2 keys

2023-01-23 12:12 UTC, bertyhell commented
this translation still contains a trailing slash:
```
  "modules/media/const/index___er-ging-iets-mis-bij-het-ophalen-van-het-afspeel-token": "Er ging iets mis bij het afspelen. Probeer het opnieuw. ",
```

2023-01-23 12:19 UTC, bertyhell approved these changes

2023-01-23 12:19 UTC, bertyhell commented on public/locales/nl/common.json
> +  "modules/admin/const/routing___mijn-materiaalaanvragen": "",
add default string for all translations with "" as value

2023-01-23 12:19 UTC, bertyhell commented on src/pages/admin/materiaalaanvragen/index.tsx
> +			<PermissionsCheck allPermissions={[]}>{renderPageContent()}</PermissionsCheck>
You can create a permission and give it the same name as the backend:
https://github.com/viaacode/hetarchief-proxy/blob/release/archief2-fase2/src/modules/users/types.ts#L53

you can add the permissions here:
https://github.com/viaacode/hetarchief-client/blob/master/src/modules/account/const/index.tsx#L90

The 2 Permission enum objects in back and frontend should stay in sync at all time

2023-01-23 13:29 UTC, merged