feat(ARC-1242): added toggle login footer
viaacode/hetarchief-client pull request #605
Opened 2023-01-11 10:37 UTC by WardVerc1

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/113892598/211784764-48ee3050-836e-4196-92ec-36828eef7a02.png">

2023-01-11 14:09 UTC, silkederudder-shd approved these changes

2023-01-23 09:25 UTC, bertyhell commented
Add env var to draaiboek docs: https://meemoo.atlassian.net/wiki/spaces/HA2/pages/3761242113/Draaiboek+ARC+Release+1.3

2023-01-23 09:25 UTC, bertyhell commented
Add env var ENABLE_LOGIN_FOOTER to .env.template file

2023-01-23 09:25 UTC, bertyhell requested changes
see global remarks

2023-01-23 09:54 UTC, bertyhell approved these changes

2023-01-23 10:12 UTC, merged