feat(ARC-1267): Add duration to thumbnail in 'mijn mappen'
viaacode/hetarchief-client pull request #618
Opened 2023-01-30 10:33 UTC by WardVerc1

<img width="563" alt="image" src="https://user-images.githubusercontent.com/113892598/215453056-8a15477a-ad96-462f-b9ad-6433f3c963a5.png">
<img width="475" alt="image" src="https://user-images.githubusercontent.com/113892598/215453120-f44b7874-e094-4c5b-9b68-8d8d48c5e2d0.png">

2023-01-30 15:26 UTC, silkederudder-shd requested changes

2023-01-30 15:26 UTC, silkederudder-shd commented on src/modules/shared/components/MediaCard/MediaCard.tsx
> +					<div className={clsx(styles['c-media-card__header-duration'])}>{duration}</div>
You could create a `renderDuration` function and reuse it on line 147.

2023-01-31 15:01 UTC, silkederudder-shd approved these changes

2023-02-03 12:25 UTC, tourlbr approved these changes

2023-02-03 13:29 UTC, bertyhell commented
if the media card doesn't show anything, it collapses. Let's add a min height of 13rem to those media cards:
c-media-card__header-wrapper

You can see this in the favorieten1 folder of the meemooadmin account on tst
![image](https://user-images.githubusercontent.com/1710840/216615118-6b140958-fbac-4cb6-b555-5231f6e74f37.png)

2023-02-03 13:30 UTC, bertyhell approved these changes

2023-02-03 14:33 UTC, merged