feature/ARC-1269: Added icons, label and tooltip for limited access map
viaacode/hetarchief-client pull request #621
Opened 2023-02-01 13:41 UTC by WardVerc1

![image](https://user-images.githubusercontent.com/113892598/216058751-e4a04ae9-3650-42b6-ac72-d90fdb6377d2.png)

2023-02-01 15:39 UTC, tourlbr requested changes

2023-02-01 15:39 UTC, tourlbr commented on src/modules/account/types/collections.ts
> +	usedForLimitedAccessUntil: string;
REQ: kan ook null zijn

2023-02-02 08:43 UTC, tourlbr approved these changes

2023-02-03 12:25 UTC, tourlbr approved these changes

2023-02-07 07:53 UTC, silkederudder-shd approved these changes

2023-02-08 11:12 UTC, merged