Feature/arc 1344
viaacode/hetarchief-client pull request #626
Opened 2023-02-13 09:36 UTC by silkederudder-shd

### Admin
(Ben je leerkracht? item should not be active on these screens, I only added this to demonstrate it)
<img width="2302" alt="admin-desktop" src="https://user-images.githubusercontent.com/77958553/218422084-ca0a6d25-0037-449d-9cca-9f4cb9b72edc.png">
<img width="428" alt="admin-mobile" src="https://user-images.githubusercontent.com/77958553/218422090-a70f7a7b-f966-47e9-b6c5-63c5cd4a7d2b.png">

### CP
<img width="2302" alt="cp-desktop" src="https://user-images.githubusercontent.com/77958553/218422229-85e22ef2-74d9-40c6-bf21-3f57451bfbf9.png">
<img width="430" alt="cp-mobile-1" src="https://user-images.githubusercontent.com/77958553/218422233-993fd490-ad9d-4fbb-9da8-b6075204eb47.png">
<img width="417" alt="cp-mobile-2" src="https://user-images.githubusercontent.com/77958553/218422234-905a65a1-716c-4d9d-b1ed-74e6dbf489e0.png">

### Logged out
<img width="2302" alt="logout-desktop" src="https://user-images.githubusercontent.com/77958553/218422280-28941355-cac0-46b9-ac4b-032e2952fe69.png">
<img width="405" alt="logout-mobile" src="https://user-images.githubusercontent.com/77958553/218422288-3bcb9766-0e42-414b-90ab-50df875d00c5.png">

2023-02-13 10:15 UTC, tourlbr commented on src/modules/navigation/components/Navigation/Navigation.consts.tsx
> +export enum NAVIGATION_DROPDOOWN {
PP: add enum to types file

2023-02-13 10:16 UTC, tourlbr approved these changes

2023-02-14 07:15 UTC, tourlbr approved these changes

2023-02-16 08:34 UTC, WardVerc1 approved these changes

2023-02-16 09:28 UTC, bertyhell commented
"Zoeken naar aanbieders" should link to "/bezoek"

![image](https://user-images.githubusercontent.com/1710840/219324011-63187fdc-f221-4390-924b-eb3a2a46ad6b.png)


Going to the search page, crashes the app. You probably need to use ?.replaceAll since the maintainer query param doesn't always have a value

![image](https://user-images.githubusercontent.com/1710840/219324378-fca37333-5366-4b75-91d6-7814c9f7f47e.png)

2023-02-16 09:32 UTC, bertyhell commented
The mobile view of the logged out homepage doesn't look completely correct:
![image](https://user-images.githubusercontent.com/1710840/219325536-0a975ee2-557c-4670-b85a-15dfef3f3c51.png)

2023-02-16 09:37 UTC, bertyhell requested changes
see global remarks

2023-02-16 09:45 UTC, silkederudder-shd commented
> see global remarks

@bertyhell, see https://meemoo.atlassian.net/browse/ARC-1376. The white line had to be removed on both the home and search page.

2023-02-16 10:32 UTC, silkederudder-shd commented
> 

![image](https://user-images.githubusercontent.com/77958553/219340772-06625e33-52fb-49aa-a46f-8029785c9426.png)

2023-02-16 13:57 UTC, bertyhell commented
The "bezoek een aanbieder should not be underlined when you're at the homepage:
![image](https://user-images.githubusercontent.com/1710840/219384388-627b00eb-dfa2-4233-a578-e0e754d923b5.png)

2023-02-16 13:58 UTC, bertyhell requested changes
see global remark

2023-02-17 09:59 UTC, bertyhell commented on src/modules/visitor-space/const/index.tsx
> +	[VisitorSpaceFilterId.Maintainer]: withDefault(StringParam, ''),
why is this needed? i would think we just omit the maintainer query param if it is empty?

2023-02-17 09:59 UTC, bertyhell approved these changes

2023-02-17 12:48 UTC, merged