feat(mijn-materiaalaanvragen): render personal material requests
viaacode/hetarchief-client pull request #630
Opened 2023-02-15 16:25 UTC by silkederudder-shd

https://user-images.githubusercontent.com/77958553/219089308-aa4c64a4-00a6-4536-9c6f-d7f3429d16bf.mov

2023-02-16 08:49 UTC, tourlbr approved these changes

2023-02-16 09:02 UTC, WardVerc1 approved these changes

2023-02-16 13:52 UTC, bertyhell commented
sorting of the date doesn't work correct after the first few times:

https://user-images.githubusercontent.com/1710840/219383096-72024463-27a5-4453-9ad9-522da9557773.mp4

2023-02-16 13:54 UTC, bertyhell requested changes
see global remark

2023-02-17 09:57 UTC, bertyhell approved these changes

2023-02-20 07:00 UTC, merged