Feature/arc 1261
viaacode/hetarchief-client pull request #639
Opened 2023-02-21 14:02 UTC by silkederudder-shd

<img width="1746" alt="image" src="https://user-images.githubusercontent.com/77958553/220366363-f1a1ec69-5a49-401f-82a0-07a8e80022f8.png">

2023-02-21 14:12 UTC, WardVerc1 approved these changes

2023-02-21 14:12 UTC, WardVerc1 commented on public/locales/nl/common.json
> +	"modules/cp/const/material-requests___aanbieder": "",
Waarom zijn deze leeg?

2023-02-21 14:21 UTC, silkederudder-shd commented on public/locales/nl/common.json
> +	"modules/cp/const/material-requests___aanbieder": "",
Dat zal er nog eentje zijn die nu pas geupdate, ik voeg een default vertaling toe.

2023-02-21 16:31 UTC, tourlbr requested changes

2023-02-21 16:31 UTC, tourlbr commented on src/modules/shared/types/visit.ts
> +	FOLDER = 'FOLDER',
REQ: Plural > FOLDERS = consistant with BE

2023-02-22 07:50 UTC, tourlbr approved these changes

2023-02-24 07:35 UTC, merged