fix(ARC-1181): fix scss overwrites
viaacode/hetarchief-client pull request #647
Opened 2023-02-27 12:09 UTC by WardVerc1

2023-02-27 15:47 UTC, tourlbr approved these changes

2023-02-28 12:28 UTC, bertyhell requested changes

2023-02-28 12:28 UTC, bertyhell commented on src/styles/components/_tooltip.scss
> -	font-size: 1.3rem;
These styles are being overridden by the avo2-components tooltip which uses the same class: .c-tooltip

A cleaner way of fixing this conflicts is to use a different class in the react-components. eg:
.c-tooltip-component

Then we avoid conflicting css rules alltogether

2023-02-28 13:45 UTC, silkederudder-shd approved these changes

2023-02-28 15:38 UTC, merged