feat(arc-1331): Add keyUser pill to MediaCard
viaacode/hetarchief-client pull request #702
Opened 2023-03-14 10:05 UTC by WardVerc1

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/113892598/224965978-7de31cb3-1040-45ef-9098-4fd9c503e37e.png">
Ticket: https://meemoo.atlassian.net/browse/ARC-1211

2023-03-14 11:42 UTC, tourlbr approved these changes

2023-03-14 14:27 UTC, silkederudder-shd requested changes

2023-03-14 14:27 UTC, silkederudder-shd commented on src/modules/shared/components/MediaCard/MediaCard.tsx
> +	const renderKeyUserPill = () => {
Add a test to check if this block is rendered correctly eg `Should render the key user pill when...`

2023-03-15 10:16 UTC, BavoVdg reviewed
Hoe moet ik dit testen?

2023-03-15 12:29 UTC, WardVerc1 commented
@BavoVdg in VisitorSpaceSearchPage, `isKeyUser: item.accessThrough?.includes(IeObjectAccessThrough.KEY_USER)` even veranderen naar `isKeyUser`

2023-03-15 14:45 UTC, silkederudder-shd approved these changes

2023-03-15 15:03 UTC, merged