Bugfix/fix tests and type errors
viaacode/hetarchief-client pull request #707
Opened 2023-03-16 11:02 UTC by silkederudder-shd

2023-03-16 11:13 UTC, tourlbr approved these changes

2023-03-16 12:54 UTC, BavoVdg requested changes
Ik heb een falende test als ik die lokaal run. 
![image](https://user-images.githubusercontent.com/85545258/225623164-6b8f745e-2a46-4422-b5e7-6ec2c970968e.png)

2023-03-16 15:32 UTC, WardVerc1 approved these changes

2023-03-17 12:10 UTC, tourlbr approved these changes
Alle testen slagen. PR kan gemerged worden

2023-03-17 12:16 UTC, merged