Feature/arc 1309
viaacode/hetarchief-client pull request #722
Opened 2023-03-21 16:31 UTC by BavoVdg

ticket: https://meemoo.atlassian.net/browse/ARC-1309
story: https://meemoo.atlassian.net/browse/ARC-1186

Added "rapporteer" blade

2023-03-21 16:51 UTC, tourlbr approved these changes

2023-03-23 13:47 UTC, silkederudder-shd requested changes

2023-03-23 13:47 UTC, silkederudder-shd commented on src/modules/shared/components/Blade/Blade.tsx
> +			if (event.key === 'Escape') {
Je kan hiervoor `keysEscape` gebruiken uit react-components.
```
import { keysEscape } from '@meemoo/react-components';
```

2023-03-23 13:47 UTC, silkederudder-shd commented on src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
> +				const isOwnVisitorSapce =
Er bestaat reeds een `useHasAnyGroup(Group.X, Group.Y)` hook die je kan gebruiken:
```
// Buiten de render fn
const isCPAdmin = useHasAnyGroup(Group.CP_ADMIN)


const isOwnVisitorSapce = isCPAdmin && visitorSpace.id === user.maintainerId;
```

2023-03-23 13:47 UTC, silkederudder-shd commented on src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
> +				<Link passHref href="/kiosk-voorwaarden">
Kunnen we hiervoor de `ROUTES` of `ROUTE_PARTS` enum niet gebruiken?

2023-03-23 13:47 UTC, silkederudder-shd commented on src/pages/zoeken/[slug]/[ie]/index.tsx
> +	const canReport = user?.groupName !== Group.KIOSK_VISITOR;
Same here, je kan die hook gebruiken :D

2023-03-27 08:10 UTC, bertyhell commented
De blade sluit niet na versturen:
> Wanneer het versturen van het bericht succesvol was zal 
>     - de blade zichzelf sluiten
>     - een notificatie worden weergegeven om de gebruiker op de hoogte te stellen van dit feit.

![image](https://user-images.githubusercontent.com/1710840/227880803-78e7c7f0-6c1e-460d-9af9-fbb96c25c0e8.png)

2023-03-27 08:59 UTC, merged