Feature/arc 1343 1300 1342 1294
viaacode/hetarchief-client pull request #777
Opened 2023-04-06 10:05 UTC by silkederudder-shd

WE WILL USE THIS BRANCH AS A "BASE". ONCE ALL SUBTASKS AND RELATED TASKS ARE READY AND MERGED INTO THIS ONE, WE CAN TEST THIS BRANCH WITH THE FOLLOWING STORIES:
- https://meemoo.atlassian.net/browse/ARC-1343
- https://meemoo.atlassian.net/browse/ARC-1300
- https://meemoo.atlassian.net/browse/ARC-1342
- https://meemoo.atlassian.net/browse/ARC-1294

2023-04-11 12:37 UTC, bertyhell requested changes
I don't see the export button when i login as cp admin (vrt) and go to an object for which i have access to the vistitor space (vlaams parlement)
![image](https://user-images.githubusercontent.com/1710840/231164349-44ede962-ae25-4f6d-9f0f-5d75c919e0bb.png)

2023-04-11 12:37 UTC, bertyhell commented on src/pages/zoeken/[slug]/[ie]/index.tsx
> +		}
shouldn't this be the inverse?
```suggestion
		if (isNil(user)) {
			return ANONYMOUS_ACTION_SORT_MAP();
		}
```

2023-04-13 07:14 UTC, silkederudder-shd commented on src/pages/zoeken/[slug]/[ie]/index.tsx
> +		}
Right 😅

2023-04-14 08:37 UTC, bertyhell commented
update: ik zie nog steeds geen export knop als ik inlog met vrt admin en surf naar http://localhost:3200/zoeken/vlaams-parlement/d8536ff53419422abebd9586ba57a2bd9375048f07fc4d2cb93907f4893cfe706bf73924a2ea418586bd6aa8f33e6857
maar mss heb je dat nog niet gefixed?

![image](https://user-images.githubusercontent.com/1710840/231991147-62a0ad03-4714-40b4-b33a-83c3306d43e1.png)

2023-04-14 11:36 UTC, silkederudder-shd commented
> update: ik zie nog steeds geen export knop als ik inlog met vrt admin en surf naar http://localhost:3200/zoeken/vlaams-parlement/d8536ff53419422abebd9586ba57a2bd9375048f07fc4d2cb93907f4893cfe706bf73924a2ea418586bd6aa8f33e6857 maar mss heb je dat nog niet gefixed?
> 
> ![image](https://user-images.githubusercontent.com/1710840/231991147-62a0ad03-4714-40b4-b33a-83c3306d43e1.png)

Ik moest dat nog oppikken, alleen zou die ertussen moeten staan als die in de sort map zit. Het kan wel zijn dat de permissies (die er al in zaten) niet voldoen waardoor de knop er dan uit gelaten wordt.

2023-04-18 09:30 UTC, bertyhell approved these changes

2023-04-18 13:13 UTC, merged