feat(arc-1168): added three clickable tiles content block
viaacode/hetarchief-client pull request #791
Opened 2023-04-14 11:29 UTC by WardVerc1

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/113892598/232031474-9351fc4f-e2ec-416f-980e-445efbce9bda.png">
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/113892598/232031650-f4cdaeac-4b4e-4f4b-bdfa-e17d6373564f.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/113892598/232031868-2f091fcc-4855-4360-ae74-7e0e3b7dd697.png">
Ticket: https://meemoo.atlassian.net/browse/ARC-1168
Admin-core PR: https://github.com/viaacode/react-admin-core-module/pull/157

2023-04-14 12:30 UTC, bertyhell commented
The block doesn't stay inside the width of the page:
![image](https://user-images.githubusercontent.com/1710840/232043726-c30dfe68-7ecd-4cb7-9b12-440de510600f.png)

I think well either have to make the tiles less wide to make everything fit the page width like in the design. Keeping the tiles square is a bonus.
![image](https://user-images.githubusercontent.com/1710840/232043858-3912e108-1e4c-4ca3-bd26-d6c3001e0091.png)

2023-04-14 12:31 UTC, bertyhell requested changes
see global remark

2023-04-18 06:06 UTC, silkederudder-shd approved these changes

2023-04-18 10:01 UTC, bertyhell requested changes

2023-04-18 10:01 UTC, bertyhell commented on src/styles/admin-core/content-blocks/_three-clickable-tiles.scss
> +$tile-size: 27rem;
pages can have different widths, so setting a hard width is not a very good solution:
![image](https://user-images.githubusercontent.com/1710840/232743069-33b3fcc4-62ed-4673-a718-79229b5ebd1a.png)
![image](https://user-images.githubusercontent.com/1710840/232743154-22351522-1096-47b0-88f1-52200529c1a9.png)

Its better to make each tile 33% wide and make the height the same as the width:
```css
.c-block-three-clickable-tiles__term {
    width: 33%;
}
.c-block-three-clickable-tiles__tile-image {
    display: flex;
    justify-content: center;
    align-content: center;
    width: 100%; // change this to 100%
    /* height: 27rem; */
    background-size: cover;
    background-position: center center;
    background-repeat: no-repeat;
    padding: 0 5rem;
    flex-wrap: wrap;
    text-align: center;
    aspect-ratio: 1 / 1; // Add aspect ratio
}
```
![image](https://user-images.githubusercontent.com/1710840/232743488-55e43452-338b-4f9e-a34e-1da4b0ff0be9.png)

2023-04-18 12:06 UTC, bertyhell approved these changes

2023-04-18 12:16 UTC, merged