bugfix/ARC-1614: added max width to table cells
viaacode/hetarchief-client pull request #829
Opened 2023-04-26 12:56 UTC by WardVerc1

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/113892598/234580920-69f1d011-2e52-47f5-bdcb-7b110a61b76a.png">
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/113892598/234580811-a49cec60-74ea-4fda-a5d0-a1b324e503e0.png">
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/113892598/234581085-9d665f59-0814-4f77-aaf5-84fcd38a23bc.png">
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/113892598/234581271-30c0142a-136f-4697-a0cb-c302cb04ce61.png">

Ticket: https://meemoo.atlassian.net/browse/ARC-1614

2023-04-26 13:05 UTC, silkederudder-shd approved these changes

2023-04-28 08:48 UTC, bertyhell commented
hmm, this makes all the columns the same width and wastes a lot of space
maybe we should just set a max length on the email adres?
like this:
```
	{
		Header: tText('modules/admin/const/requests___emailadres'),
		accessor: 'visitorMail',
		Cell: ({ row }: VisitRow) => (
			<CopyButton
				className="u-color-neutral u-p-0 c-table__copy"
				icon={undefined}
				variants="text"
				text={row.original.visitorMail}
				title={row.original.visitorMail}
			>
				{truncate(row.original.visitorMail, { length: 35 })}
			</CopyButton>
		),
	},
```

By also setting a title we can ensure the full email is still readable by hovering over it

![image](https://user-images.githubusercontent.com/1710840/235101197-cd96a89e-a0b5-4963-96b7-eaea52711682.png)

2023-04-28 08:50 UTC, bertyhell requested changes
see global remark

2023-04-28 09:32 UTC, bertyhell approved these changes

2023-04-28 11:58 UTC, bertyhell commented
This pr is replaced with https://github.com/viaacode/hetarchief-client/pull/837 because it has less visual impact. 

This PR:
* sets the width of all columns to the same width
* ensures that the action buttons are always clickable

The other PR https://github.com/viaacode/hetarchief-client/pull/837
* Only limits the width of the email addresses
* has less visual impact
* still has problems with action buttons not being clickable on screensizes between small desktop and phone widths

2023-04-28 11:58 UTC, closed without merging