fix(arc-1644): fix onclick taglist + go to selected maintainer
viaacode/hetarchief-client pull request #870
Opened 2023-05-05 12:35 UTC by WardVerc1

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/113892598/236458576-95029230-5eec-4c72-a2ea-d4ced5ddf7d8.png">
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/113892598/236458674-3c4e5c3e-34c4-4940-a938-7908c0bb6d89.png">
Ticket: https://meemoo.atlassian.net/browse/ARC-1644

2023-05-08 08:01 UTC, bertyhell requested changes

2023-05-09 06:31 UTC, silkederudder-shd requested changes
See remark from Bert.

2023-05-09 06:31 UTC, silkederudder-shd commented on src/modules/shared/components/MediaCard/MediaCard.tsx
> +				onClick={() => saveSlug()}
```suggestion
				onClick={saveSlug}
```

2023-05-10 12:17 UTC, bertyhell commented on src/modules/shared/components/MediaCard/MediaCard.tsx
> +		console.log('saveslug');
remove console.log
and probably this whole handler is not needed anymore

2023-05-12 09:17 UTC, silkederudder-shd approved these changes

2023-05-12 09:34 UTC, merged