fix(arc-1645): land on most recent active visit search page
viaacode/hetarchief-client pull request #876
Opened 2023-05-08 09:39 UTC by WardVerc1

<img width="950" alt="image" src="https://user-images.githubusercontent.com/113892598/236791047-ef3e9940-422c-4084-be33-1c5869470cbd.png">
Ticket: https://meemoo.atlassian.net/browse/ARC-1645

2023-05-09 06:43 UTC, silkederudder-shd requested changes

2023-05-09 06:43 UTC, silkederudder-shd commented on src/modules/navigation/components/Navigation/Navigation.consts.tsx
> +				? `${contentPath}?aanbieder=${activeVisits[0].spaceSlug}`
Will `activeVisits[0].spaceSlug` always be filled up? Maybe add a fallback in case it doesn't.

2023-05-09 06:43 UTC, silkederudder-shd commented on src/modules/shared/layouts/AppLayout/AppLayout.tsx
> +		const { items: spaces } = await VisitsService.getAll({
Add empty line above this block

2023-05-09 06:43 UTC, silkederudder-shd commented on src/modules/shared/layouts/AppLayout/AppLayout.tsx
> +		if (!user || [GroupName.KIOSK_VISITOR, GroupName.ANONYMOUS].includes(user.groupName)) {
There's a hook you can use for this:
```
const canX = useHasAnyGroup(GroupName.KIOSK_VISITOR, GroupName.ANONYMOUS);

if (!user || canX) ....
```

2023-05-10 11:55 UTC, bertyhell requested changes

2023-05-10 11:55 UTC, bertyhell commented on src/modules/shared/layouts/AppLayout/AppLayout.tsx
> +	}, [getVisitorSpaces, isLoggedIn]);
You should use the react-query hook:
```
useGetAllActiveVisits
```

You can use the enabled option to enable/disable the hook:
```
enabled: user && ![GroupName.KIOSK_VISITOR, GroupName.ANONYMOUS].includes(user.groupName)
```

and set de default sort to
```
			orderProp: 'endAt',
			orderDirection: OrderDirection.desc,
```

2023-05-10 11:55 UTC, bertyhell commented on src/modules/shared/layouts/AppLayout/AppLayout.tsx
> +		getVisitorSpaces();
just for clarity:
visit space is not the same thing as a visit request

one is a representation of a physical room that someone can visit
and the other is a request to visit the room at a certain date

So this function would be called: getActiveVisitRequests()

But like stated below => its better to use the hook: useGetAllActiveVisits

2023-05-10 11:55 UTC, bertyhell commented on src/modules/shared/layouts/AppLayout/AppLayout.tsx
> +			orderDirection: OrderDirection.asc,
You want descending here.
Higher dates => low dates
recent dates => to older dates
```suggestion
			orderDirection: OrderDirection.desc,
```


https://github.com/viaacode/hetarchief-client/assets/1710840/e3bb1696-d5b4-4017-86e1-071cd59a39bd

2023-05-12 09:18 UTC, silkederudder-shd approved these changes

2023-05-12 09:46 UTC, bertyhell commented
doesn't seem to work for the base user:
https://github.com/viaacode/hetarchief-client/assets/1710840/4b4743dc-5273-4be2-b851-62eba52ca730

2023-05-12 09:46 UTC, bertyhell requested changes
see global remark

2023-05-12 11:05 UTC, bertyhell approved these changes

2023-05-12 11:05 UTC, merged