feat: trigger events
viaacode/hetarchief-client pull request #924
Opened 2023-05-23 11:23 UTC by silkederudder-shd

2023-05-23 13:26 UTC, WardVerc1 approved these changes

2023-05-24 13:25 UTC, bertyhell requested changes

2023-05-24 13:25 UTC, bertyhell commented on src/pages/zoeken/[slug]/[ie]/index.tsx
> +			EventsService.triggerEvent(LogEventType.BEZOEK_ITEM_VIEW, path, eventData);
> Mogen blijven bestaan (deze worden enkel uitgestuurd als het gaat om een sessie waar bezoekertool actief is, en de eindgebruiker een item binnen de bezoekertool zoekt of raadpleegt):

So we should wrap this Visit event inside a mediaInfo.accessThrough.includes('VISIT...')?

2023-05-25 13:07 UTC, bertyhell requested changes

2023-05-25 13:07 UTC, bertyhell commented on src/pages/zoeken/[slug]/[ie]/index.tsx
> +			EventsService.triggerEvent(LogEventType.BEZOEK_ITEM_PLAY, path, eventData);
```suggestion
			EventsService.triggerEvent(LogEventType.ITEM_PLAY, path, eventData);
```

2023-05-25 13:08 UTC, bertyhell approved these changes

2023-05-25 13:08 UTC, merged